name: incloud

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          cache: 'go'
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev 
        


      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/katana/cmd/katana@latest
        shell: bash
        
      - name: Cache ProjectDiscovery tools
        uses: actions/cache@v2
        with:
          cache: 'tools'
          path: /home/runner/tools
          key: ${{ runner.os }}-go-tools

        
      - name: Setup Dependencies
        run: katana -d 1 -u http://www.baidu.com 
